- name: Create the kube-apiserver service
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  notify: Reload systemd daemon

- name: Enable the kube-apiserver service
  service:
    name: kube-apiserver
    enabled: yes

- name: Create the kube-controller-manager service
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  notify: Reload systemd daemon

- name: Enable the kube-controller-manager service
  service:
    name: kube-controller-manager
    enabled: yes

- name: Create the kube-scheduler config file
  template:
    src: kube-scheduler.yaml.j2
    dest: /etc/kubernetes/config/kube-scheduler.yaml

- name: Create the kube-scheduler service
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
  notify: Reload systemd daemon

- name: Enable the kube-scheduler service
  service:
    name: kube-scheduler
    enabled: yes
