kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ok0Joa5afLUtLkQPhY+IlfjJLr5cwiKojyRt14FW1tw=
      - identity: {}