- name: Create the etcd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: Reload systemd daemon

- name: Enable the etcd service
  service:
    name: etcd
    enabled: yes

- name: Mount the etcd data directory
  mount:
    path: /var/lib/etcd
    src: /dev/vdb
    fstype: ext4
    state: mounted
