grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    hosts: ["grafana.scc-incubator.scc.suse.de"]
    tls: []

prometheus:
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    hosts: ["prometheus.scc-incubator.scc.suse.de"]
    tls: []
