- name: Containerd Config
  template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml

- name: Create the containerd server
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  notify: Reload systemd daemon

- name: Enable the containerd service
  service:
    name: containerd
    enabled: yes

- name: Kubelet Config
  template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml

- name: Create the kubelet server
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify: Reload systemd daemon

- name: Enable the kubelet service
  service:
    name: kubelet
    enabled: yes

- name: Kube Proxy Config
  template:
    src: kube-proxy-config.yaml.j2
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml

- name: Create the kube proxy service
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  notify: Reload systemd daemon

- name: Enable the kube-proxy service
  service:
    name: kube-proxy
    enabled: yes
